spring:
  application:
    name: shopping-microservice
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
shopping-microservice:
  greeting: "Dev"
  default-value: "World"